
# Site settings
title: Huaigu Li
name: Huaigu Li
subtitle:  PhD Student 
email: hli723@gatech.edu
description: >
   PhD Student
baseurl: ""
url: "https://pesoto.github.io/"
github_username:  LiHuaigu
disqus_baseurl: "https://pesoto.github.io/"
disqus_shortname: https-pesoto-github-io
permalink: :title
#google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Huaigu Li"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: LiHuaigu
    url: https://github.com/LiHuaigu
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Huaigu Li
    url: https://www.linkedin.com/in/huaigu-li-8a60a1144/
    desc: Connect with me on LinkedIn
    share: true
